DELETE FROM USERS;
DELETE FROM USER_ROLES;
DELETE FROM USER_FAVORITES;
DELETE FROM MENU_APIS;
DELETE FROM RESTAURANTS;
DELETE FROM MENU_ITEMS;
DELETE FROM CARBOHYDRATE_ESTIMATES;
DELETE FROM OUTCOMES;